name: TheBridge
main: plugily.projects.thebridge.Main
authors: [2Wild4You, Tigerpanzer]
version: 0.0.1
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  thebridge:
    description: thebridge commands
    aliases: [tb, bridge]
  thebridgeAdmin:
    description: thebridge admin commands
    aliases: [tba, bridgeadmin]