name: Publish Master Branch

on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4.2.2
        with:
          ref: 'master'
      - name: Set up JDK
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: jdk
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew publishMavenPublicationToReleasesRepository
        env:
          MAVEN_USERNAME: ${{ secrets.RELEASESUSERNAME }}
          MAVEN_PASSWORD: ${{ secrets.RELEASESPASSWORD }}
